### ISSUE TITLE
Doesn't work on OS X 10.7.4 with node v0.8.4

### ISSUE THREAD

**Issue by dawn110110** [pgriess/wsbench#7]
$ node wsbench ws:// localhost:8989/track

/Users/dawn110110/code/wsbench/wsbench/lib/optparse.js:144
    while(l-- > 0) if(LONG_SWITCH_RE(arr[l])) return true;
                      ^
TypeError: object is not a function
    at contains_expr (/Users/dawn110110/code/wsbench/wsbench/lib/optparse.js:144:23)
    at build_rules (/Users/dawn110110/code/wsbench/wsbench/lib/optparse.js:77:13)
    at Object.OptionParser.parse (/Users/dawn110110/code/wsbench/wsbench/lib/optparse.js:224:21)
    at Object.<anonymous> (/Users/dawn110110/code/wsbench/wsbench/wsbench:113:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
